### ISSUE TITLE
Таблица пользователей

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/generate_game#4]
В таблице хранится вся информация о пользователе

```
users:
  id_user: int
  login: text
  password: text
  email: text
  name: text
```
