### ISSUE TITLE
Таблица игр

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/generate_game#5]
В таблице хранится информация о всех созданных играх

```
games:
  id_game: int
  name: text
  description: text
  id_user: int - author
  rate: numeric(32,2) 
```
