### ISSUE TITLE
Таблица сессий игр

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/generate_game#6]
В таблице хранится история прохождения игр пользователями.
Основная таблица хранящая в себе состояние всех сессий игр пользователей.

```
session:
  id_session: int
  id_user: int
  id_game: int
  stage: int - Сколько вопросов пройдено
  id_question: int - Какой вопрос текущий 
  rate: float - Количество очков за игру 
  time_begin: timestamp - Время начала игры
  time_end: timestamp - Время окончания игры 
  end: bool - закончилась ли игра? 

```
