### ISSUE TITLE
Таблица вопросов

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/generate_game#7]
В таблице содержится список вопросов, которые могут быть выбраны для игры 

```
question:
  id_question: int
  id_game: int
  name: text
  description: text
  answer_1: text
  answer_2: text
  image: text
  answer_1_action: hstore
  answer_2_action: hstore
```
